/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BridgeDeal {
  'contract' : string,
  'dealNumber' : bigint,
  'expectedScore' : bigint,
  'pcValue' : bigint,
  'tricksTaken' : bigint,
  'timestamp' : bigint,
  'declarer' : string,
  'actualScore' : bigint,
  'impScore' : bigint,
}
export interface BridgeDeal__1 {
  'contract' : string,
  'dealNumber' : bigint,
  'expectedScore' : bigint,
  'pcValue' : bigint,
  'tricksTaken' : bigint,
  'timestamp' : Time,
  'declarer' : string,
  'actualScore' : bigint,
  'impScore' : bigint,
}
export interface CanastaRound {
  'timestamp' : bigint,
  'weScore' : bigint,
  'roundNumber' : bigint,
  'nsScore' : bigint,
}
export interface CanastaRound__1 {
  'timestamp' : Time,
  'weScore' : bigint,
  'roundNumber' : bigint,
  'nsScore' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GameData {
  'createdAt' : Time,
  'finalScore' : [] | [bigint],
  'gameType' : GameType,
}
export type GameType = { 'bridge' : null } |
  { 'canasta' : null };
export interface Map { 'root' : Tree, 'size' : bigint }
export interface Map_1 { 'root' : Tree_1, 'size' : bigint }
export interface Map_2 { 'root' : Tree_2, 'size' : bigint }
export interface Map_3 { 'root' : Tree_3, 'size' : bigint }
export interface Map_4 { 'root' : Tree_4, 'size' : bigint }
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Text = string;
export type Time = bigint;
export type Tree = { 'red' : [Tree, Text, GameData, Tree] } |
  { 'leaf' : null } |
  { 'black' : [Tree, Text, GameData, Tree] };
export type Tree_1 = { 'red' : [Tree_1, Text, boolean, Tree_1] } |
  { 'leaf' : null } |
  { 'black' : [Tree_1, Text, boolean, Tree_1] };
export type Tree_2 = {
    'red' : [Tree_2, Text, Array<CanastaRound__1>, Tree_2]
  } |
  { 'leaf' : null } |
  { 'black' : [Tree_2, Text, Array<CanastaRound__1>, Tree_2] };
export type Tree_3 = { 'red' : [Tree_3, Text, bigint, Tree_3] } |
  { 'leaf' : null } |
  { 'black' : [Tree_3, Text, bigint, Tree_3] };
export type Tree_4 = { 'red' : [Tree_4, Text, Array<BridgeDeal__1>, Tree_4] } |
  { 'leaf' : null } |
  { 'black' : [Tree_4, Text, Array<BridgeDeal__1>, Tree_4] };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__bridgeDeals' : ActorMethod<[], Map_4>,
  '__canastaDealers' : ActorMethod<[], Map_3>,
  '__canastaRounds' : ActorMethod<[], Map_2>,
  '__gameCodes' : ActorMethod<[], Map_1>,
  '__games' : ActorMethod<[], Map>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGame' : ActorMethod<[string, GameType], undefined>,
  'finishGame' : ActorMethod<[string, bigint], undefined>,
  'generateGameCode' : ActorMethod<[string], string>,
  'getAllGames' : ActorMethod<[], Array<[string, GameData]>>,
  'getBridgeDeals' : ActorMethod<[string], Array<BridgeDeal__1>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanastaRounds' : ActorMethod<[string], Array<CanastaRound__1>>,
  'getGame' : ActorMethod<[string], [] | [GameData]>,
  'getNextDealer' : ActorMethod<[string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveBridgeDeal' : ActorMethod<[string, BridgeDeal__1], undefined>,
  'saveCanastaRound' : ActorMethod<[string, CanastaRound__1], undefined>,
  'updateBridgeDeal' : ActorMethod<
    [string, bigint, string, string, bigint, bigint, bigint, bigint, bigint],
    [] | [BridgeDeal]
  >,
  'updateCanastaRound' : ActorMethod<
    [string, bigint, bigint, bigint],
    [] | [CanastaRound]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];