/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tree = IDL.Rec();
export const Tree_1 = IDL.Rec();
export const Tree_2 = IDL.Rec();
export const Tree_3 = IDL.Rec();
export const Tree_4 = IDL.Rec();
export const Text = IDL.Text;
export const Time = IDL.Int;
export const BridgeDeal__1 = IDL.Record({
  'contract' : IDL.Text,
  'dealNumber' : IDL.Nat,
  'expectedScore' : IDL.Int,
  'pcValue' : IDL.Int,
  'tricksTaken' : IDL.Nat,
  'timestamp' : Time,
  'declarer' : IDL.Text,
  'actualScore' : IDL.Int,
  'impScore' : IDL.Int,
});
Tree_4.fill(
  IDL.Variant({
    'red' : IDL.Tuple(Tree_4, Text, IDL.Vec(BridgeDeal__1), Tree_4),
    'leaf' : IDL.Null,
    'black' : IDL.Tuple(Tree_4, Text, IDL.Vec(BridgeDeal__1), Tree_4),
  })
);
export const Map_4 = IDL.Record({ 'root' : Tree_4, 'size' : IDL.Nat });
Tree_3.fill(
  IDL.Variant({
    'red' : IDL.Tuple(Tree_3, Text, IDL.Nat, Tree_3),
    'leaf' : IDL.Null,
    'black' : IDL.Tuple(Tree_3, Text, IDL.Nat, Tree_3),
  })
);
export const Map_3 = IDL.Record({ 'root' : Tree_3, 'size' : IDL.Nat });
export const CanastaRound__1 = IDL.Record({
  'timestamp' : Time,
  'weScore' : IDL.Int,
  'roundNumber' : IDL.Nat,
  'nsScore' : IDL.Int,
});
Tree_2.fill(
  IDL.Variant({
    'red' : IDL.Tuple(Tree_2, Text, IDL.Vec(CanastaRound__1), Tree_2),
    'leaf' : IDL.Null,
    'black' : IDL.Tuple(Tree_2, Text, IDL.Vec(CanastaRound__1), Tree_2),
  })
);
export const Map_2 = IDL.Record({ 'root' : Tree_2, 'size' : IDL.Nat });
Tree_1.fill(
  IDL.Variant({
    'red' : IDL.Tuple(Tree_1, Text, IDL.Bool, Tree_1),
    'leaf' : IDL.Null,
    'black' : IDL.Tuple(Tree_1, Text, IDL.Bool, Tree_1),
  })
);
export const Map_1 = IDL.Record({ 'root' : Tree_1, 'size' : IDL.Nat });
export const GameType = IDL.Variant({
  'bridge' : IDL.Null,
  'canasta' : IDL.Null,
});
export const GameData = IDL.Record({
  'createdAt' : Time,
  'finalScore' : IDL.Opt(IDL.Int),
  'gameType' : GameType,
});
Tree.fill(
  IDL.Variant({
    'red' : IDL.Tuple(Tree, Text, GameData, Tree),
    'leaf' : IDL.Null,
    'black' : IDL.Tuple(Tree, Text, GameData, Tree),
  })
);
export const Map = IDL.Record({ 'root' : Tree, 'size' : IDL.Nat });
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BridgeDeal = IDL.Record({
  'contract' : IDL.Text,
  'dealNumber' : IDL.Nat,
  'expectedScore' : IDL.Int,
  'pcValue' : IDL.Int,
  'tricksTaken' : IDL.Nat,
  'timestamp' : IDL.Int,
  'declarer' : IDL.Text,
  'actualScore' : IDL.Int,
  'impScore' : IDL.Int,
});
export const CanastaRound = IDL.Record({
  'timestamp' : IDL.Int,
  'weScore' : IDL.Int,
  'roundNumber' : IDL.Nat,
  'nsScore' : IDL.Int,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__bridgeDeals' : IDL.Func([], [Map_4], ['query']),
  '__canastaDealers' : IDL.Func([], [Map_3], ['query']),
  '__canastaRounds' : IDL.Func([], [Map_2], ['query']),
  '__gameCodes' : IDL.Func([], [Map_1], ['query']),
  '__games' : IDL.Func([], [Map], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGame' : IDL.Func([IDL.Text, GameType], [], []),
  'finishGame' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'generateGameCode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllGames' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, GameData))], []),
  'getBridgeDeals' : IDL.Func([IDL.Text], [IDL.Vec(BridgeDeal__1)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanastaRounds' : IDL.Func([IDL.Text], [IDL.Vec(CanastaRound__1)], []),
  'getGame' : IDL.Func([IDL.Text], [IDL.Opt(GameData)], []),
  'getNextDealer' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveBridgeDeal' : IDL.Func([IDL.Text, BridgeDeal__1], [], []),
  'saveCanastaRound' : IDL.Func([IDL.Text, CanastaRound__1], [], []),
  'updateBridgeDeal' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
      ],
      [IDL.Opt(BridgeDeal)],
      [],
    ),
  'updateCanastaRound' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Int, IDL.Int],
      [IDL.Opt(CanastaRound)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tree = IDL.Rec();
  const Tree_1 = IDL.Rec();
  const Tree_2 = IDL.Rec();
  const Tree_3 = IDL.Rec();
  const Tree_4 = IDL.Rec();
  const Text = IDL.Text;
  const Time = IDL.Int;
  const BridgeDeal__1 = IDL.Record({
    'contract' : IDL.Text,
    'dealNumber' : IDL.Nat,
    'expectedScore' : IDL.Int,
    'pcValue' : IDL.Int,
    'tricksTaken' : IDL.Nat,
    'timestamp' : Time,
    'declarer' : IDL.Text,
    'actualScore' : IDL.Int,
    'impScore' : IDL.Int,
  });
  Tree_4.fill(
    IDL.Variant({
      'red' : IDL.Tuple(Tree_4, Text, IDL.Vec(BridgeDeal__1), Tree_4),
      'leaf' : IDL.Null,
      'black' : IDL.Tuple(Tree_4, Text, IDL.Vec(BridgeDeal__1), Tree_4),
    })
  );
  const Map_4 = IDL.Record({ 'root' : Tree_4, 'size' : IDL.Nat });
  Tree_3.fill(
    IDL.Variant({
      'red' : IDL.Tuple(Tree_3, Text, IDL.Nat, Tree_3),
      'leaf' : IDL.Null,
      'black' : IDL.Tuple(Tree_3, Text, IDL.Nat, Tree_3),
    })
  );
  const Map_3 = IDL.Record({ 'root' : Tree_3, 'size' : IDL.Nat });
  const CanastaRound__1 = IDL.Record({
    'timestamp' : Time,
    'weScore' : IDL.Int,
    'roundNumber' : IDL.Nat,
    'nsScore' : IDL.Int,
  });
  Tree_2.fill(
    IDL.Variant({
      'red' : IDL.Tuple(Tree_2, Text, IDL.Vec(CanastaRound__1), Tree_2),
      'leaf' : IDL.Null,
      'black' : IDL.Tuple(Tree_2, Text, IDL.Vec(CanastaRound__1), Tree_2),
    })
  );
  const Map_2 = IDL.Record({ 'root' : Tree_2, 'size' : IDL.Nat });
  Tree_1.fill(
    IDL.Variant({
      'red' : IDL.Tuple(Tree_1, Text, IDL.Bool, Tree_1),
      'leaf' : IDL.Null,
      'black' : IDL.Tuple(Tree_1, Text, IDL.Bool, Tree_1),
    })
  );
  const Map_1 = IDL.Record({ 'root' : Tree_1, 'size' : IDL.Nat });
  const GameType = IDL.Variant({ 'bridge' : IDL.Null, 'canasta' : IDL.Null });
  const GameData = IDL.Record({
    'createdAt' : Time,
    'finalScore' : IDL.Opt(IDL.Int),
    'gameType' : GameType,
  });
  Tree.fill(
    IDL.Variant({
      'red' : IDL.Tuple(Tree, Text, GameData, Tree),
      'leaf' : IDL.Null,
      'black' : IDL.Tuple(Tree, Text, GameData, Tree),
    })
  );
  const Map = IDL.Record({ 'root' : Tree, 'size' : IDL.Nat });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BridgeDeal = IDL.Record({
    'contract' : IDL.Text,
    'dealNumber' : IDL.Nat,
    'expectedScore' : IDL.Int,
    'pcValue' : IDL.Int,
    'tricksTaken' : IDL.Nat,
    'timestamp' : IDL.Int,
    'declarer' : IDL.Text,
    'actualScore' : IDL.Int,
    'impScore' : IDL.Int,
  });
  const CanastaRound = IDL.Record({
    'timestamp' : IDL.Int,
    'weScore' : IDL.Int,
    'roundNumber' : IDL.Nat,
    'nsScore' : IDL.Int,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__bridgeDeals' : IDL.Func([], [Map_4], ['query']),
    '__canastaDealers' : IDL.Func([], [Map_3], ['query']),
    '__canastaRounds' : IDL.Func([], [Map_2], ['query']),
    '__gameCodes' : IDL.Func([], [Map_1], ['query']),
    '__games' : IDL.Func([], [Map], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGame' : IDL.Func([IDL.Text, GameType], [], []),
    'finishGame' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'generateGameCode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllGames' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, GameData))], []),
    'getBridgeDeals' : IDL.Func([IDL.Text], [IDL.Vec(BridgeDeal__1)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanastaRounds' : IDL.Func([IDL.Text], [IDL.Vec(CanastaRound__1)], []),
    'getGame' : IDL.Func([IDL.Text], [IDL.Opt(GameData)], []),
    'getNextDealer' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveBridgeDeal' : IDL.Func([IDL.Text, BridgeDeal__1], [], []),
    'saveCanastaRound' : IDL.Func([IDL.Text, CanastaRound__1], [], []),
    'updateBridgeDeal' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
        ],
        [IDL.Opt(BridgeDeal)],
        [],
      ),
    'updateCanastaRound' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Int, IDL.Int],
        [IDL.Opt(CanastaRound)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };