/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface BridgeDeal__1 {
    contract: string;
    dealNumber: bigint;
    expectedScore: bigint;
    pcValue: bigint;
    tricksTaken: bigint;
    timestamp: Time;
    declarer: string;
    actualScore: bigint;
    impScore: bigint;
}
export type Time = bigint;
export interface CanastaRound__1 {
    timestamp: Time;
    weScore: bigint;
    roundNumber: bigint;
    nsScore: bigint;
}
export interface Map_4 {
    root: Tree_4;
    size: bigint;
}
export type Tree_2 = {
    __kind__: "red";
    red: [Tree_2, Text, Array<CanastaRound__1>, Tree_2];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_2, Text, Array<CanastaRound__1>, Tree_2];
};
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type Tree_3 = {
    __kind__: "red";
    red: [Tree_3, Text, bigint, Tree_3];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_3, Text, bigint, Tree_3];
};
export interface CanastaRound {
    timestamp: bigint;
    weScore: bigint;
    roundNumber: bigint;
    nsScore: bigint;
}
export type Tree = {
    __kind__: "red";
    red: [Tree, Text, GameData, Tree];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree, Text, GameData, Tree];
};
export type Text = string;
export interface Map_3 {
    root: Tree_3;
    size: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Map_1 {
    root: Tree_1;
    size: bigint;
}
export type Tree_4 = {
    __kind__: "red";
    red: [Tree_4, Text, Array<BridgeDeal__1>, Tree_4];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_4, Text, Array<BridgeDeal__1>, Tree_4];
};
export interface GameData {
    createdAt: Time;
    finalScore?: bigint;
    gameType: GameType;
}
export interface BridgeDeal {
    contract: string;
    dealNumber: bigint;
    expectedScore: bigint;
    pcValue: bigint;
    tricksTaken: bigint;
    timestamp: bigint;
    declarer: string;
    actualScore: bigint;
    impScore: bigint;
}
export interface Map_2 {
    root: Tree_2;
    size: bigint;
}
export type Tree_1 = {
    __kind__: "red";
    red: [Tree_1, Text, boolean, Tree_1];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_1, Text, boolean, Tree_1];
};
export interface Map_ {
    root: Tree;
    size: bigint;
}
export enum GameType {
    bridge = "bridge",
    canasta = "canasta"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __bridgeDeals(): Promise<Map_4>;
    __canastaDealers(): Promise<Map_3>;
    __canastaRounds(): Promise<Map_2>;
    __gameCodes(): Promise<Map_1>;
    __games(): Promise<Map_>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGame(code: string, gameType: GameType): Promise<void>;
    finishGame(code: string, finalScore: bigint): Promise<void>;
    generateGameCode(userInput: string): Promise<string>;
    getAllGames(): Promise<Array<[string, GameData]>>;
    getBridgeDeals(gameCode: string): Promise<Array<BridgeDeal__1>>;
    getCallerUserRole(): Promise<UserRole>;
    getCanastaRounds(gameCode: string): Promise<Array<CanastaRound__1>>;
    getGame(code: string): Promise<GameData | null>;
    getNextDealer(gameCode: string): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    saveBridgeDeal(gameCode: string, deal: BridgeDeal__1): Promise<void>;
    saveCanastaRound(gameCode: string, round: CanastaRound__1): Promise<void>;
    updateBridgeDeal(gameCode: string, dealIndex: bigint, contract: string, declarer: string, tricksTaken: bigint, pcValue: bigint, expectedScore: bigint, actualScore: bigint, impScore: bigint): Promise<BridgeDeal | null>;
    updateCanastaRound(gameCode: string, roundIndex: bigint, nsScore: bigint, weScore: bigint): Promise<CanastaRound | null>;
}
import type { BridgeDeal as _BridgeDeal, BridgeDeal__1 as _BridgeDeal__1, CanastaRound as _CanastaRound, CanastaRound__1 as _CanastaRound__1, Error as _Error, GameData as _GameData, GameType as _GameType, Map as _Map, Map_1 as _Map_1, Map_2 as _Map_2, Map_3 as _Map_3, Map_4 as _Map_4, Result as _Result, Text as _Text, Time as _Time, Tree as _Tree, Tree_1 as _Tree_1, Tree_2 as _Tree_2, Tree_3 as _Tree_3, Tree_4 as _Tree_4, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __bridgeDeals(): Promise<Map_4> {
        if (this.processError) {
            try {
                const result = await this.actor.__bridgeDeals();
                return from_candid_Map_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__bridgeDeals();
            return from_candid_Map_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async __canastaDealers(): Promise<Map_3> {
        if (this.processError) {
            try {
                const result = await this.actor.__canastaDealers();
                return from_candid_Map_3_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__canastaDealers();
            return from_candid_Map_3_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async __canastaRounds(): Promise<Map_2> {
        if (this.processError) {
            try {
                const result = await this.actor.__canastaRounds();
                return from_candid_Map_2_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__canastaRounds();
            return from_candid_Map_2_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async __gameCodes(): Promise<Map_1> {
        if (this.processError) {
            try {
                const result = await this.actor.__gameCodes();
                return from_candid_Map_1_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__gameCodes();
            return from_candid_Map_1_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async __games(): Promise<Map_> {
        if (this.processError) {
            try {
                const result = await this.actor.__games();
                return from_candid_Map_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__games();
            return from_candid_Map_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGame(arg0: string, arg1: GameType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(arg0, to_candid_GameType_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(arg0, to_candid_GameType_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async finishGame(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finishGame(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishGame(arg0, arg1);
            return result;
        }
    }
    async generateGameCode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateGameCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateGameCode(arg0);
            return result;
        }
    }
    async getAllGames(): Promise<Array<[string, GameData]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBridgeDeals(arg0: string): Promise<Array<BridgeDeal__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBridgeDeals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBridgeDeals(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanastaRounds(arg0: string): Promise<Array<CanastaRound__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanastaRounds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanastaRounds(arg0);
            return result;
        }
    }
    async getGame(arg0: string): Promise<GameData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextDealer(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextDealer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextDealer(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveBridgeDeal(arg0: string, arg1: BridgeDeal__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBridgeDeal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBridgeDeal(arg0, arg1);
            return result;
        }
    }
    async saveCanastaRound(arg0: string, arg1: CanastaRound__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCanastaRound(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCanastaRound(arg0, arg1);
            return result;
        }
    }
    async updateBridgeDeal(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint): Promise<BridgeDeal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBridgeDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBridgeDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCanastaRound(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<CanastaRound | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCanastaRound(arg0, arg1, arg2, arg3);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCanastaRound(arg0, arg1, arg2, arg3);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Error_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_GameData_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameData): GameData {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_GameType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameType): GameType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Map_1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Map_1): Map_1 {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Map_2_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Map_2): Map_2 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Map_3_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Map_3): Map_3 {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Map_4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Map_4): Map_4 {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Map_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Map): Map_ {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Tree_1_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tree_1): Tree_1 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Tree_2_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tree_2): Tree_2 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Tree_3_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tree_3): Tree_3 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Tree_4_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tree_4): Tree_4 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Tree_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tree): Tree {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameData]): GameData | null {
    return value.length === 0 ? null : from_candid_GameData_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BridgeDeal]): BridgeDeal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CanastaRound]): CanastaRound | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    root: _Tree_2;
    size: bigint;
}): {
    root: Tree_2;
    size: bigint;
} {
    return {
        root: from_candid_Tree_2_n13(_uploadFile, _downloadFile, value.root),
        size: value.size
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    root: _Tree_1;
    size: bigint;
}): {
    root: Tree_1;
    size: bigint;
} {
    return {
        root: from_candid_Tree_1_n18(_uploadFile, _downloadFile, value.root),
        size: value.size
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    root: _Tree_4;
    size: bigint;
}): {
    root: Tree_4;
    size: bigint;
} {
    return {
        root: from_candid_Tree_4_n3(_uploadFile, _downloadFile, value.root),
        size: value.size
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    root: _Tree;
    size: bigint;
}): {
    root: Tree;
    size: bigint;
} {
    return {
        root: from_candid_Tree_n23(_uploadFile, _downloadFile, value.root),
        size: value.size
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Time;
    finalScore: [] | [bigint];
    gameType: _GameType;
}): {
    createdAt: Time;
    finalScore?: bigint;
    gameType: GameType;
} {
    return {
        createdAt: value.createdAt,
        finalScore: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.finalScore)),
        gameType: from_candid_GameType_n29(_uploadFile, _downloadFile, value.gameType)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    root: _Tree_3;
    size: bigint;
}): {
    root: Tree_3;
    size: bigint;
} {
    return {
        root: from_candid_Tree_3_n8(_uploadFile, _downloadFile, value.root),
        size: value.size
    };
}
function from_candid_tuple_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Tree_3, _Text, bigint, _Tree_3]): [Tree_3, Text, bigint, Tree_3] {
    return [
        from_candid_Tree_3_n8(_uploadFile, _downloadFile, value[0]),
        value[1],
        value[2],
        from_candid_Tree_3_n8(_uploadFile, _downloadFile, value[3])
    ];
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Tree_2, _Text, Array<_CanastaRound__1>, _Tree_2]): [Tree_2, Text, Array<CanastaRound__1>, Tree_2] {
    return [
        from_candid_Tree_2_n13(_uploadFile, _downloadFile, value[0]),
        value[1],
        value[2],
        from_candid_Tree_2_n13(_uploadFile, _downloadFile, value[3])
    ];
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Tree_1, _Text, boolean, _Tree_1]): [Tree_1, Text, boolean, Tree_1] {
    return [
        from_candid_Tree_1_n18(_uploadFile, _downloadFile, value[0]),
        value[1],
        value[2],
        from_candid_Tree_1_n18(_uploadFile, _downloadFile, value[3])
    ];
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Tree, _Text, _GameData, _Tree]): [Tree, Text, GameData, Tree] {
    return [
        from_candid_Tree_n23(_uploadFile, _downloadFile, value[0]),
        value[1],
        from_candid_GameData_n26(_uploadFile, _downloadFile, value[2]),
        from_candid_Tree_n23(_uploadFile, _downloadFile, value[3])
    ];
}
function from_candid_tuple_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _GameData]): [string, GameData] {
    return [
        value[0],
        from_candid_GameData_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Tree_4, _Text, Array<_BridgeDeal__1>, _Tree_4]): [Tree_4, Text, Array<BridgeDeal__1>, Tree_4] {
    return [
        from_candid_Tree_4_n3(_uploadFile, _downloadFile, value[0]),
        value[1],
        value[2],
        from_candid_Tree_4_n3(_uploadFile, _downloadFile, value[3])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: [_Tree_2, _Text, Array<_CanastaRound__1>, _Tree_2];
} | {
    leaf: null;
} | {
    black: [_Tree_2, _Text, Array<_CanastaRound__1>, _Tree_2];
}): {
    __kind__: "red";
    red: [Tree_2, Text, Array<CanastaRound__1>, Tree_2];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_2, Text, Array<CanastaRound__1>, Tree_2];
} {
    return "red" in value ? {
        __kind__: "red",
        red: from_candid_tuple_n15(_uploadFile, _downloadFile, value.red)
    } : "leaf" in value ? {
        __kind__: "leaf",
        leaf: value.leaf
    } : "black" in value ? {
        __kind__: "black",
        black: from_candid_tuple_n15(_uploadFile, _downloadFile, value.black)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: [_Tree_1, _Text, boolean, _Tree_1];
} | {
    leaf: null;
} | {
    black: [_Tree_1, _Text, boolean, _Tree_1];
}): {
    __kind__: "red";
    red: [Tree_1, Text, boolean, Tree_1];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_1, Text, boolean, Tree_1];
} {
    return "red" in value ? {
        __kind__: "red",
        red: from_candid_tuple_n20(_uploadFile, _downloadFile, value.red)
    } : "leaf" in value ? {
        __kind__: "leaf",
        leaf: value.leaf
    } : "black" in value ? {
        __kind__: "black",
        black: from_candid_tuple_n20(_uploadFile, _downloadFile, value.black)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: [_Tree, _Text, _GameData, _Tree];
} | {
    leaf: null;
} | {
    black: [_Tree, _Text, _GameData, _Tree];
}): {
    __kind__: "red";
    red: [Tree, Text, GameData, Tree];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree, Text, GameData, Tree];
} {
    return "red" in value ? {
        __kind__: "red",
        red: from_candid_tuple_n25(_uploadFile, _downloadFile, value.red)
    } : "leaf" in value ? {
        __kind__: "leaf",
        leaf: value.leaf
    } : "black" in value ? {
        __kind__: "black",
        black: from_candid_tuple_n25(_uploadFile, _downloadFile, value.black)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bridge: null;
} | {
    canasta: null;
}): GameType {
    return "bridge" in value ? GameType.bridge : "canasta" in value ? GameType.canasta : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n33(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: [_Tree_4, _Text, Array<_BridgeDeal__1>, _Tree_4];
} | {
    leaf: null;
} | {
    black: [_Tree_4, _Text, Array<_BridgeDeal__1>, _Tree_4];
}): {
    __kind__: "red";
    red: [Tree_4, Text, Array<BridgeDeal__1>, Tree_4];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_4, Text, Array<BridgeDeal__1>, Tree_4];
} {
    return "red" in value ? {
        __kind__: "red",
        red: from_candid_tuple_n5(_uploadFile, _downloadFile, value.red)
    } : "leaf" in value ? {
        __kind__: "leaf",
        leaf: value.leaf
    } : "black" in value ? {
        __kind__: "black",
        black: from_candid_tuple_n5(_uploadFile, _downloadFile, value.black)
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: [_Tree_3, _Text, bigint, _Tree_3];
} | {
    leaf: null;
} | {
    black: [_Tree_3, _Text, bigint, _Tree_3];
}): {
    __kind__: "red";
    red: [Tree_3, Text, bigint, Tree_3];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree_3, Text, bigint, Tree_3];
} {
    return "red" in value ? {
        __kind__: "red",
        red: from_candid_tuple_n10(_uploadFile, _downloadFile, value.red)
    } : "leaf" in value ? {
        __kind__: "leaf",
        leaf: value.leaf
    } : "black" in value ? {
        __kind__: "black",
        black: from_candid_tuple_n10(_uploadFile, _downloadFile, value.black)
    } : value;
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _GameData]>): Array<[string, GameData]> {
    return value.map((x)=>from_candid_tuple_n40(_uploadFile, _downloadFile, x));
}
function to_candid_GameType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): _GameType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): {
    bridge: null;
} | {
    canasta: null;
} {
    return value == GameType.bridge ? {
        bridge: null
    } : value == GameType.canasta ? {
        canasta: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
